name: Compile and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.10
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup Compile Dependencies
        run: |
          python -m pip install --upgrade pyinstaller
      - name: Setup Code Dependencies
        run: |
          python -m pip install --upgrade -r ./workflowHelper/requirements.txt
      - name: Setup Version File
        run: |
          python ./workflowHelper/exeVersion.py
      - name: Compile Package
        run: |
          python ./workflowHelper/build.py
      - name: Test Executable
        run: |
          ./bin/catw.exe -h
          ./bin/catw.exe -v
          ./bin/catw.exe -p ./bin/catw.exe -R -d
      - name: Show and Push
        run: |
          git status
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./bin/exeVersionFile
          git add ./bin/catw.exe
          git commit -m "🤖Compiled Binary."
          git push origin HEAD:main
        continue-on-error: true