name: Compile Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      f_suffix: ${{ matrix.os == 'macos-latest' && '_darwin' || matrix.os == 'windows-latest' && '_windows.exe' || '_linux' }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - name: Install Python 3.10
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Update PIP
        run: |
          python -m pip install --upgrade pip
      - name: Setup Compile Dependencies
        run: |
          python -m pip install --upgrade pyinstaller
      - name: Setup Code Dependencies
        run: |
          python -m pip install --upgrade -r ./workflowHelper/requirements.txt
      - name: Setup Version File
        run: |
          python -m workflowHelper.exeversion
      - name: Compile Package
        run: |
          python -m workflowHelper.build
      - name: Test Executable ${{ matrix.os }}
        run: |
          ./bin/catw${{ env.f_suffix }} -h
          ./bin/catw${{ env.f_suffix }} -v
          ./bin/catw${{ env.f_suffix }} -p ./bin/catw${{ env.f_suffix }} -R --debug
      - name: Show Changes
        run: |
          git status
      - name: Commit Changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./bin/*
          git commit -m "🤖Compiled Binary for ${{ matrix.os }}."
          git push origin HEAD:dev
        continue-on-error: true
