name: Build and Check

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - name: Test Code Execution
        if: ${{ matrix.python-version != '3.11' || matrix.os != 'macos-latest' }}
        run: |
          python -m pip install --upgrade -r ./cat_win/requirements.txt
          python -m cat_win.cat -v
      - name: Check and Build Package
        run: |
          python -m build
      - name: Install Local Package
        run: python ./tests/dist.py