name: Build and Check

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Setup Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - name: Setup Code Dependencies
        run: |
          python -m pip install --upgrade -r ./cat_win/requirements.txt
      - name: Test Code Execution
        run: |
          python -m cat_win.cat -h
          python -m cat_win -v
          python -m cat_win -p -n **/cat.config --nocolor
      - name: Check and Build Package
        run: |
          python -m build
      - name: Install Local Package
        run: |
          python ./workflowHelper/dist.py
      - name: Test Entrypoint
        run: |
          catw -v
          cat -v