name: Build and Check Packages

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/package_test.yml
      - cat_win/**
      - workflowHelper/**
    # only trigger on development branch
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        # python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9', 'pypy-3.10']
        python-version: ['3.6', '3.10', '3.13', 'pypy-3.10']
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - name: Install Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Update PIP
        run: |
          python -m pip install --upgrade pip
      - name: Setup Build Dependencies
        run: |
          python -m pip install --upgrade build
      - name: Check and Build Package
        run: |
          python -m build
      - name: Install Local Package
        # this should also install the code dependency in requirements.txt
        run: |
          python -m workflowHelper.dist 
      - name: Test Code Execution
        run: |
          python -m cat_win
          python -m cat_win -v
          python -m cat_win -p -nf **/r*.txt --nocolor
      - name: Test Entrypoint
        run: |
          catw -v
      - name: Setup Clipboard Dependency
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pyperclip3
          python -m pip install --upgrade pyperclip
          sudo apt-get install xclip
          sudo apt install wl-clipboard
      - name: Test Clipboard Ability
        run: |
          catw -pn **/r*.txt --clip --debug
