name: Build and Check

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/**
      - cat_win/**
      - tests/**
      - workflowHelper/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'pip'
      - name: Setup Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      # - name: Setup Code Dependencies
      #   run: |
      #     python -m pip install --upgrade -r ./cat_win/requirements.txt
      - name: Check and Build Package
        run: |
          python -m build
      - name: Install Local Package
        run: |
          python ./workflowHelper/dist.py
      - name: Test Code Execution
        run: |
          python -m cat_win.cat -h
          python -m cat_win -v
          python -m cat_win -p -nf **/r*.txt --nocolor
      - name: Test Entrypoint
        run: |
          catw -v
      - name: Setup Clipboard Dependency
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install xclip
          sudo apt install wl-clipboard
      - name: Test Clipboard Ability
        run: |
          catw -pn **/r*.txt --clip -d