name: Generate Social Preview

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.10
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup Image Dependencies
        run: |
          python -m pip install --upgrade Pillow
      - name: Generate image
        run: |
          python ./workflowHelper/preview.py
      - name: Show and Push
        run: |
          git status
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./img/socialPreview.png
          git commit -m "🤖Generated Social Preview."
          git push origin main