name: Unittests

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/unit_test.yml
      - cat_win/**
      - workflowHelper/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.7, '3.10', 'pypy-3.8']
    steps:
      - name: Set Windows Line Ending
        run: |
          git config --global core.autocrlf true
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Setup Test Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r ./workflowHelper/requirements.txt
      - name: Start UnitTests
        run: |
          python -m unittest discover -s cat_win.tests -p test*.py