name: Unittests

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/unit_test.yml
      - cat_win/**
      - workflowHelper/**
    # only trigger on development branch
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.6', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9', 'pypy-3.10']
        # python-version: ['3.8', '3.9', '3.11', 'pypy-3.8', 'pypy-3.10']
        exclude:
          - os: macos-latest
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: 'pypy-3.6'
          - os: macos-latest
            python-version: 'pypy-3.7'
          - os: windows-latest
            python-version: 'pypy-3.6'
          - os: ubuntu-latest
            python-version: '3.6'
        include:
          - os: macos-13
            python-version: '3.6'
          - os: macos-13
            python-version: '3.7'
          - os: macos-13
            python-version: 'pypy-3.6'
          - os: macos-13
            python-version: 'pypy-3.7'
          - os: windows-2019
            python-version: 'pypy-3.6'
          - os: ubuntu-20.04
            python-version: '3.6'
    steps:
      - name: Set Windows Line Ending
        run: |
          git config --global core.autocrlf true
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - name: Install Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Update PIP
        run: |
          python -m pip install --upgrade pip
      - name: Setup Test Dependencies
        run: |
          python -m pip install --upgrade -r ./workflowHelper/requirements.txt
      - name: Start UnitTests
        run: |
          python -m unittest discover -s cat_win.tests -p test*.py
